"""Derive ``config/taxonomy.yaml`` from the generated SOP corpus.

BUILD-TIME ONLY.

Build order matters here and is deliberate (``BUILD.md`` S8): the corpus is
authored first, and the taxonomy is derived from it. Writing the classes first and
then authoring SOPs to fit them would produce a corpus shaped to flatter the
classifier -- clean boundaries, no overlap, no awkward cases -- and the evaluation
would measure that flattery rather than the problem.

The generated file is therefore a **projection, not a source**. It exists so the
taxonomy is readable and diffable in one place, and so training and evaluation
have a stable list of class names. The runtime does not read it: ``sop/index.py``
derives the same maps from frontmatter at startup, so there is exactly one source
of truth and no file to fall out of date.

``scripts/check_taxonomy.py`` asserts the two agree; it runs in the test suite.

Usage:
    python scripts/derive_taxonomy.py           # write config/taxonomy.yaml
    python scripts/derive_taxonomy.py --check   # fail if the file is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Final

import yaml

ROOT: Final[Path] = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from triage.sop.index import BUCKETS, NO_SUPPORTING_SOP, build_index  # noqa: E402

OUT_PATH: Final[Path] = ROOT / "config" / "taxonomy.yaml"

#: Held-out classes have no indexed SOP, so nothing in the corpus names them.
#: They are still part of the taxonomy -- the classifier must predict them, and
#: they must appear in the label list -- so they are declared here, with the SOP
#: that would serve them if it were re-indexed.
HELD_OUT: Final[dict[str, str]] = {
    "rental_income": "SOP-INC-001",
    "foreign_income_dta": "SOP-INC-002",
}

HEADER: Final[str] = """\
# THE TAXONOMY -- 12 classes, 5 routing buckets.
#
# GENERATED by scripts/derive_taxonomy.py from data/sop/*.md. Do not edit.
#
# This file is a PROJECTION of the corpus, not a source. The runtime derives the
# same maps from SOP frontmatter at startup (src/triage/sop/index.py), so there is
# one source of truth and no file here to fall out of date. This copy exists to
# make the taxonomy readable and diffable in one place, and to give training and
# evaluation a stable list of class names.
#
# To change routing behaviour, edit the SOP spec and regenerate. That is the point
# of the design: escalation policy lives in the corpus, so an agency conforming
# real internal SOPs to this schema changes behaviour with no code change.
#
# Regenerate:  python scripts/generate_sops.py && python scripts/derive_taxonomy.py
"""

#: Why each bucket routes the way it does. Policy rationale, not derivable from
#: any single document, so it is authored here and carried into the generated file
#: -- the escalation policy has to be readable and arguable in one place.
BUCKET_RATIONALE: Final[dict[str, str]] = {
    "auto_answerable": (
        "Draft a reply if calibrated confidence clears the threshold. These are "
        "the only classes where the agent asserts substantive tax content."
    ),
    "requires_account_lookup": (
        "Always escalate. Answering requires reading a specific taxpayer's record, "
        "which the agent cannot do and must not guess at."
    ),
    "high_consequence": (
        "Always escalate regardless of confidence. Financial distress and active "
        "fraud carry consequences no confidence score should be permitted to "
        "authorise an automated answer for."
    ),
    "out_of_scope": (
        "Auto-reply with a redirect, never a guess. The redirect is an automated "
        "action and counts toward coverage: under the no-back-door policy a clean "
        "redirect is the correct outcome, not a failure."
    ),
    "no_supporting_sop": (
        "Always escalate. Derived, not hand-mapped: the class resolves to no "
        "indexed SOP, so the emptiness of the lookup is itself the signal."
    ),
}


def derive() -> dict[str, Any]:
    """Build the taxonomy document from the corpus."""
    index = build_index()
    classes: dict[str, Any] = {}

    for cls in sorted(index.class_to_sops):
        sops = index.sops_for(cls)
        classes[cls] = {
            "bucket": index.bucket_for(cls),
            "sops": [s.sop_id for s in sops],
            "auto_reply_permitted": all(s.auto_reply_permitted for s in sops),
            "escalate_if": sorted({t for s in sops for t in s.escalation_triggers}),
            "indexed": True,
        }

    for cls, sop_id in HELD_OUT.items():
        classes[cls] = {
            "bucket": NO_SUPPORTING_SOP,
            "sops": [],
            "auto_reply_permitted": False,
            "escalate_if": [NO_SUPPORTING_SOP],
            "indexed": False,
            "held_out_sop": sop_id,
            "note": (
                "Authored but excluded from the index, so this class is genuinely "
                "unanswerable and the router derives no_supporting_sop."
            ),
        }

    buckets = {
        bucket: {
            "classes": sorted(c for c, meta in classes.items() if meta["bucket"] == bucket),
            "rationale": BUCKET_RATIONALE[bucket],
        }
        for bucket in BUCKETS
    }

    return {
        "classes": dict(sorted(classes.items())),
        "buckets": buckets,
        "labels": sorted(classes),
    }


def render(doc: dict[str, Any]) -> str:
    return HEADER + "\n" + yaml.safe_dump(doc, sort_keys=False, width=88, allow_unicode=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args()

    text = render(derive())

    if args.check:
        if not OUT_PATH.exists():
            print(f"MISSING: {OUT_PATH}. Run: python scripts/derive_taxonomy.py", file=sys.stderr)
            return 1
        if OUT_PATH.read_text(encoding="utf-8") != text:
            print(f"STALE: {OUT_PATH} does not match the corpus.\n"
                  "Run: python scripts/derive_taxonomy.py", file=sys.stderr)
            return 1
        print(f"{OUT_PATH.relative_to(ROOT)} is current")
        return 0

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(text, encoding="utf-8")
    doc = derive()
    print(f"wrote {OUT_PATH.relative_to(ROOT)}: {len(doc['labels'])} classes, "
          f"{len(doc['buckets'])} buckets")
    for bucket, meta in doc["buckets"].items():
        print(f"  {bucket:24} {len(meta['classes'])} classes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
